
init-config:
  country-name: malaysia
  bank-name : Alliance Bank
  format-id: alliance_bank_my_1
  format-key-word: ''

# parsing variables
summary-config:
  summary-page-index: 0
  keys: ['account-number', 'account-type', 'bank-name', 'document-type', 'number-of-pages', 'statement-date']
  bank-name-find: ['Alliance Bank']
  account-list: ['CURRENT A/C - OTHERS']
  separate-summary-lines: True
  requires-space-separation: True
  account-name-start: 'Statement Date'
  account-name-line-start-index: 2
  account-name-line-end-index: 2
  account-address-line-start-index: 3
  account-address-stop: []
  account-address-stop-at-name: True
  state-dt-keyword: 'Statement Date'
  no-of-date-words: 1
  page-keyword: Page
  account-no-keyword: 'Account No.'
  account-no-regex: '\d\d\d\d\d\d\d\d\d\d\d\d\d\d\d'

transaction-config:
  txn-key-word: ['BEGINNING BALANCE', 'ENDING BALANCE']
  txn-remove-date: ['BEGINNING BALANCE', 'ENDING BALANCE']
  start-of-month-keyword: ['BEGINNING BALANCE']
  end-of-month-keyword: ['ENDING BALANCE']
  stop-at: ['The items and balances shown above will be deemed correct', 'TOTAL DEBIT/CREDIT']
  date-regex-list: ['\d\d\d\d\d\d']
  txn-remove: ['Protected by PIDM']
  txn-description-include-additional-column: True
  last-column-headings: ['Tarikh', 'Keterangan Urusniaga', 'No. Cek']
  page-last-transaction-index: -1
  page-first-transaction-index: 0
  columns-in-between-date-descriptions: 0
  statement-date-format: 'DD/MM/YYYY'
  transaction-date-format: 'DDMMYY'
  number-regex-list: ['([0-9sS$oO§]{1,3}(,[0-9sS$oO§]{3})*(\.|\,)[0-9sS$oO§]{2})']
  txn-type-in-money-value: False
  date-joined-with-transaction: True
  balance-outside-table-key-word: ['BEGINNING BALANCE', 'ENDING BALANCE']
  balance-in-separate-table: True
  balance-fields: {
    'key': ['BEGINNING BALANCE', 'ENDING BALANCE', 'TOTAL DEBIT', 'TOTAL CREDIT'],
    'actual-key': ['TOTAL DEBIT', 'TOTAL CREDIT'],
    'row-after-key': 0,
  }
  transaction-summary-key-info: [{
    keyword: ['TOTAL CREDIT'],
    key: 'total-credit'
  }, {
    keyword: ['TOTAL DEBIT'],
    key: 'total-debit'
  }, {
    keyword: ['BEGINNING BALANCE'],
    key: 'start-balance'
  }, {
    keyword: ['ENDING BALANCE'],
    key: 'close-balance'
  }]