
init-config:
  country-name: malaysia
  bank-name : CIMB
  format-id: cimb_my_native

# parsing variables
summary-config:
  summary-page-index: 0
  keys: ['account-number', 'account-type', 'bank-name', 'document-type', 'number-of-pages', 'statement-date']
  bank-name-find: ['Bank Berhad', 'CIMB']
  account-list: ['Current Account-i', 'Current Account']
  separate-summary-lines: True
  requires-space-separation: True
  account-name-start: 'Page / Halaman'
  account-name-line-start-index: 1
  account-name-line-end-index: 1
  account-address-line-start-index: 3
  account-address-stop: ['Transaction Details']
  page-keyword: Page
  state-dt-keyword: Statement Date
  no-of-date-words: 1
  account-no-regex: '\d\d\-\d\d\d\d\d\d\d\-\d'

transaction-config:
  txn-reverse-chronological: True
  txn-key-word: ['Opening Balance', 'CLOSING BALANCE']
  start-of-month-keyword: ['Opening Balance']
  end-of-month-keyword: ['Total Deposits']
  stop-at: ['CONTINUE NEXT PAGE', 'CLOSING BALANCE', 'No of Withdrawal', 'No of Deposits', 'Total Withdrawal', 'Total Deposits', 'End of Statement']
  date-regex-list: ['\d\d/\d\d/\d\d\d\d']
  columns-in-between-date-descriptions: 0
  statement-date-format: 'DD/MM/YYYY'
  transaction-date-format: 'DD/MM/YYYY'
  number-regex-list: ['([0-9sS$oO§]{1,3}(,[0-9sS$oO§]{3})*(\.|\,)[0-9sS$oO§]{2})']
  txn-type-in-money-value: False
  date-joined-with-transaction: True
  balance-outside-table-key-word: []
  balance-in-separate-table: True
  balance-fields: {
    'key': ['No of Withdrawal', 'No of Deposit', 'Total Withdrawal', 'Total Deposits'],
    'actual-key': ['Total Withdrawal', 'Total Deposits'],
    'row-after-key': 2,
    'column': [3,4]
  }
  balance-columns: [ 3, 4 ]
  transaction-summary-key-info: [{
    keyword: ['Total Deposits'],
    key: 'total-credit'
  }, {
    keyword: ['Total Withdrawal'],
    key: 'total-debit'
  }, {
    keyword: ['Opening Balance'],
    key: 'start-balance'
  }, {
    keyword: ['CLOSING BALANCE'],
    key: 'close-balance'
  }]