
init-config:
  country-name: singapore
  bank-name : DBS
  format-id: dbs_sg_1

# parsing variables
summary-config:
  summary-page-index: 0
  keys: ['account-number', 'account-type', 'bank-name', 'document-type', 'number-of-pages', 'statement-date']
  bank-name-find: ['DBS']
  account-list: ['SGD CURRENT ACCOUNT']
  separate-summary-lines: True
  account-no-address: True
  account-name-start: 'Account Name :'
  account-name-line-start-index: 0
  account-name-line-end-index: 0
  account-name-end: '-'
  state-dt-keyword: 'Ledger Balance'
  state-dt-regex: '\d\d-[a-zA-Z][a-zA-Z][a-zA-Z]-\d\d\d\d'
  page-keyword: Page
  account-no-keyword: 'Account Number :'
  account-no-regex: '\d\d\d\d\d\d\d\d\d\d'

cropped-summary-areas:
  crop-account-name-address-area:
    coordinates: [240, 360, 700, 1654]

transaction-config:
  txn-key-word: []
  txn-remove-date: []
  start-of-month-keyword: ['Opening Balance']
  end-of-month-keyword: []
  stop-at: ['Printed By']
  date-regex-list: ['\d\d\-[a-zA-Z][a-zA-Z][a-zA-Z]-\d\d\d\d']
  columns-in-between-date-descriptions: 1
  statement-date-format: 'DD-MMM-YYYY'
  transaction-date-format: 'DD-MMM-YYYY'
  number-regex-list: ['([0-9sS$oO§]{1,3}(,[0-9sS$oO§]{3})*(\.|\,)[0-9sS$oO§]{2})']
  txn-type-in-money-value: False
  date-joined-with-transaction: True
  balance-outside-table-key-word: ['Opening Balance', 'Ledger Balance', 'Total Debit Amount', 'Total Credit Amount']
  balance-in-separate-table: True
  balance-fields: {
    'key': ['Opening Balance', 'Ledger Balance', 'Available Balance', 'Total Debit Amount', 'Total Credit Amount'],
    'actual-key': ['Opening Balance', 'Ledger Balance', 'Total Debit Amount', 'Total Credit Amount'],
    'row-after-key': 0,
  }
  transaction-summary-key-info: [{
    keyword: ['Total Credit Amount'],
    key: 'total-credit'
  }, {
    keyword: ['Total Debit Amount'],
    key: 'total-debit'
  }, {
    keyword: ['Opening Balance'],
    key: 'start-balance'
  }, {
    keyword: ['Ledger Balance'],
    key: 'close-balance'
  }]