
init-config:
  country-name: malaysia
  bank-name : Maybank
  line-start: 15
  y_padding: 15
  y_delta: 2
  format-id: maybank_my
  format-key-word: 'Berhad'

img-processing:
  align-template: "template_file/maybank_temp.jpg"
  document-type: ~



# parsing variables
summary-config:
  keys: ['account-number','account-type','bank-address','bank-name','document-type','number-of-pages','statement-date']
  bank-name-find: ['Banking Berhad', 'Islamic Berhad','Maybank']
  bank-add-find: ['Menara', 'Malaysia','Jalan']
  address-start-line: 0
  no-of-addr-lines: 0
  account-list: ['PERSONAL SAVER-i','CORPORATE CURRENT ACCOUNT','PREMIER MUDHARABAH ACCOUNT','SME FIRST INVESTMENT ACCOUNT -I','CCA SME FIRST ACCOUNT','SME FIRST ACCOUNT -I', 'CURRENT ACCOUNT-I']
  page-keyword: PAGE
  state-dt-regex: '\d\d/\d\d/\d\d'
  no-of-date-words: null
  account-holder-addr-label: 
    label: ['STATEMENT DATE']
    index: 0
    extra-line: 4
  account-holder-name-label: 
    label: ['結單日期']
    index: 0
    extra-line: 1
  account-number-label: 
    label: ['ACCOUNT']
    index: 0
    extra-line: -1

cropped-areas: 12

cropped-summary-areas:
  crop-account-number-area: 
    field-name: account-number
    coordinates: [500,1000,1200,null]
    label: 'AKAUN'
    value-different-line-from-label: True
    label-value-index: [1,2]

transaction-config:
  txn-key-word: ['ENDING BALANCE', 'LEDGER BALANCE', 'TOTAL DEBIT', 'TOTAL CREDIT', 'PROFIT OUTSTANDING', 'BEGINNING BALANCE']
  start-of-month-keyword: ['BEGINNING BALANCE']
  end-of-month-keyword: ['TOTAL CREDIT','PROFIT OUTSTANDING']
  stop-at: [' TRANSFER FUNDS ', 'KIJANG EMAS', 'BAKILEGAR', 'LEGAR', 'PURCHASE IN', 'VISIT ANY', '.MAYBANK.COM.MY', 'M2U', 'MAYBANK2U', 'NEAREST MAYBANK', 'TERMS AND CONDITIONS','PROFIT OUTSTANDING','FEES PAYABLE','BAYARAN PERLU DIBAYAR TIDAK']
  date-regex-list: ['\d\d/\d\d/\d\d[a-zA-Z]+','\d\d/\d\d', '\d\d/\d', '[a-zA-Z][a-zA-Z]/[a-zA-Z][a-zA-Z]$', '\d\d/\d\d/\d\d\d\d\s']
  last-column-headings: ['ENTRY DATE', 'VALUE DATE', 'TRANSACTION DESCRIPTION', 'GST TYPE', 'TRANSACTION AMOUNT', 'STATEMENT BALANCE']
  page-last-transaction-index: -1
  page-first-transaction-index: 0
  columns-in-between-date-descriptions: 0
  statement-date-format: 'DD/MM/YY'
  transaction-date-format: 'DD/MM'
  number-regex-list: ['(\.\d\d(\+|\-))','(\.\d\d)','([0-9sS$oO§]{1,3}(,[0-9sS$oO§]{3})*(\.|\,)[0-9sS$oO§]{2})']
  txn-type-in-money-value: True
  date-joined-with-transaction: False
  balance-outside-table-key-word: []
  balance-in-separate-table: False
  balance-fields: {}
  transaction-summary-key-info: [{
    keyword: ['TOTAL CREDIT'],
    key: 'total-credit'
  }, {
    keyword: ['TOTAL DEBIT'],
    key: 'total-debit'
  }, {
    keyword: ['BEGINNING BALANCE'],
    key: 'start-balance'
  }, {
    keyword: ['ENDING BALANCE'],
    key: 'close-balance'
  }]

start-of-statement: 'BEGINNING BALANCE'
end-of-statement:  ['BEGINNING BALANCE','ENDING BALANCE','LEDGER BALANCE','TOTAL DEBIT','TOTAL CREDIT']