
init-config:
  country-name: singapore
  bank-name : OCBC
  format-id: ocbc_sg_2

# parsing variables
summary-config:
  summary-page-index: 0
  keys: ['account-number', 'account-type', 'bank-name', 'document-type', 'number-of-pages', 'statement-date']
  bank-name-find: ['OCBC']
  account-list: ['BUSINESS FIRST ACCOUNT - LITE', 'CURRENT ACCOUNT', 'BUSINESS ENTREPRENEUR ACCOUNT']
  separate-summary-lines: True
  requires-space-separation: True
  account-name-address-remove: ['STATEMENT', 'Page', 'For enquiries, please call', 'Business Banking', 'Customer Service Officers', 'OCBC']
  account-name-start: 'both sides of the page'
  account-address-stop: ['ACCOUNT']
  state-dt-keyword: ' ACCOUNT'
  no-of-date-words: 3
  page-keyword: Page
  account-no-keyword: 'Account No.'
  account-no-regex: '\d\d\d\d\d\d\d\d\d\d\d\d'

cropped-summary-areas:
  crop-account-name-address-area:
    coordinates: [210, 620, 0, 630]

transaction-config:
  txn-key-word: ['BALANCE B/F', 'BALANCE C/F']
  txn-remove-date: ['BALANCE B/F', 'BALANCE C/F']
  start-of-month-keyword: ['BALANCE B/F']
  end-of-month-keyword: ['Total Deposits']
  stop-at: ['Please turn over', 'RNB', 'Deposit Insurance', 'CHECK YOUR STATEMENT', 'Total Withdrawals/Deposits', 'OCBC PROMOTION & INFORMATION']
  date-regex-list: ['\d\d\s[a-zA-Z][a-zA-Z][a-zA-Z]']
  last-column-headings: [ 'Date', 'Description', 'Cheque', 'Withdrawal', 'Deposit', 'Balance']
  page-last-transaction-index: -1
  page-first-transaction-index: 0
  columns-in-between-date-descriptions: 1
  statement-date-format: 'DD MMM YYYY'
  transaction-date-format: 'DD MMM'
  number-regex-list: ['([0-9sS$oO§]{1,3}(,[0-9sS$oO§]{3})*(\.|\,)[0-9sS$oO§]{2})']
  txn-type-in-money-value: False
  date-joined-with-transaction: True
  balance-outside-table-key-word: ['Total Withdrawals/Deposits']
  balance-in-separate-table: True
  balance-fields: {
    'key': ['Total Withdrawals/Deposits'],
    'actual-key': ['Total Withdrawals', 'Total Deposits'],
    'row-after-key': 0,
  }
  transaction-summary-key-info: [{
    keyword: ['Total Deposits'],
    key: 'total-credit'
  }, {
    keyword: ['Total Withdrawals'],
    key: 'total-debit'
  }, {
    keyword: [ 'BALANCE B/F' ],
    key: 'start-balance'
  }, {
    keyword: [ 'BALANCE C/F' ],
    key: 'close-balance'
  }]