
init-config:
  country-name: singapore
  bank-name : UOB
  format-id: uob_sg_1
  format-key-word: 'Statement of Account'

# parsing variables
summary-config:
  summary-page-index: 0
  summary-scanned: True
  add-initial-summary: True
  separate-summary-lines: True
  keys: ['account-number', 'account-type', 'bank-name', 'document-type', 'number-of-pages', 'statement-date']
  bank-name-find: ['UOB']
  account-list: ['CORPORATE', 'BizTransact']
  account-name-address-remove: ['Contact Us', 'Call', '+65']
  account-name-start: ']'
  account-name-line-start-index: 1
  account-address-stop: ['Email', 'Page']
  page-keyword: Page
  state-dt-keyword: Period
  no-of-date-words: 3
  account-no-regex: '\d\d\d\-\d\d\d\-\d\d\d\-\d'

cropped-summary-areas:
  crop-account-name-address-area:
    coordinates: [0, 600, 170, 920]

transaction-config:
  txn-reverse-chronological: False
  txn-key-word: ['BALANCE B/F']
  txn-remove-date: ['BALANCE B/F']
  start-of-month-keyword: ['BALANCE B/F']
  end-of-month-keyword: ['Total']
  stop-at: ['Total', 'End of Transaction Details']
  date-regex-list: ['\d\d\s[a-zA-Z][a-zA-Z][a-zA-Z]']
  columns-in-between-date-descriptions: 0
  statement-date-format: 'DD MMM YYYY'
  transaction-date-format: 'DD MMM'
  number-regex-list: ['([0-9sS$oO§]{1,3}(,[0-9sS$oO§]{3})*(\.|\,)[0-9sS$oO§]{2})']
  txn-type-in-money-value: False
  date-joined-with-transaction: True
  balance-outside-table-key-word: []
  balance-in-separate-table: True
  balance-fields: {
    'key': ['Total Withdrawals', 'Total Deposits', 'Total'],
    'actual-key': ['Total Withdrawals', 'Total Deposits', 'Total'],
    'row-after-key': 0,
  }
  transaction-summary-key-info: [{
    keyword: ['Total Deposits'],
    key: 'total-credit'
  }, {
    keyword: ['Total Withdrawals'],
    key: 'total-debit'
  }, {
    keyword: ['BALANCE B/F'],
    key: 'start-balance'
  }, {
    keyword: ['Total'],
    key: 'close-balance'
  }]