
init-config:
  country-name: malaysia
  bank-name : UOB
  format-id: uob_my_1
  format-key-word: 'Account Activities'

# parsing variables
summary-config:
  summary-page-index: 0
  keys: ['account-number', 'account-type', 'bank-name', 'document-type', 'number-of-pages', 'statement-date']
  bank-name-find: ['UOB']
  account-list: ['Current Account']
  separate-summary-lines: True
  requires-space-separation: True
  account-name-start: ''
  account-name-line-start-index: 1
  account-name-line-end-index: 1
  account-address-line-start-index: 2
  account-address-stop: ['Page']
  state-dt-keyword: 'A/C Number'
  no-of-date-words: 3
  page-keyword: Page
  account-no-regex: '\d\d\d-\d\d\d-\d\d\d-\d'
  balance-postprocessing-opening-balance: True
  opening-balance-key-word: 'BALANCE B/F'
  balance-postprocessing-closing-balance: True

transaction-config:
  txn-key-word: ['BALANCE B/F', 'BALANCE C/F']
  txn-remove-date: ['BALANCE B/F', 'BALANCE C/F']
  start-of-month-keyword: []
  end-of-month-keyword: ['Total Withdrawals']
  stop-at: ['Notifikasi', 'Ringkasan Akaun']
  date-regex-list: ['\d\d\s[a-zA-Z][a-zA-Z][a-zA-Z]']
  transaction-date-index: 1
  columns-in-between-date-descriptions: 1
  statement-date-format: 'DD MMM YYYY'
  transaction-date-format: 'DD MMM'
  number-regex-list: ['([0-9sS$oO§]{1,3}(,[0-9sS$oO§]{3})*(\.|\,)[0-9sS$oO§]{2})']
  txn-type-in-money-value: False
  date-joined-with-transaction: True
  balance-outside-table-key-word: ['Total Withdrawals', 'Total Deposits']
  balance-in-separate-table: True
  balance-fields: {
    'key': ['Total Withdrawals', 'Total Deposits', 'Overdraft Limit'],
    'actual-key': ['Total Withdrawals', 'Total Deposits'],
    'row-after-key': 0,
  }
  transaction-summary-key-info: [{
    keyword: ['Total Deposits'],
    key: 'total-credit'
  }, {
    keyword: ['Total Withdrawals'],
    key: 'total-debit'
  }]